services:
  # 1. Service d'IA
  ai_service:
    build: ./ai_service
    expose: 
      - "8080"

  # 2. Backend (API)
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      AI_SERVICE_URL: http://ai_service:8080 
    depends_on:
      - ai_service

  # 3. Frontend (Client)
  frontend:
    build: ./frontend
    ports:
      - "80:80" 
    depends_on:
      - backend
